name: Building
on: [push, pull_request]

jobs:
  test:
    name: Building AKSideMenu Example
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 12.0.0
      - name: Cache libraries
        uses: actions/cache@v2          
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Dependencies (CocoaPods Action)
        run: |
          pod install --project-directory=AKSideMenuExamples/Simple --repo-update
        shell: bash
      - name: Building iOS Simple app
        run: exec ./.github/scripts/build_app.sh simple
      - name: Building iOS Storyboard app
        run: exec ./.github/scripts/build_app.sh storyboard        
